import { useQuery } from "@tanstack/react-query";
import { useLocalSearchParams, useRouter } from "expo-router";
import { ActivityIndicator, ScrollView, Text, View } from "react-native";

import { api } from "@/src/api";
import { Icon, Pill, PrimaryButton, ScreenHeader, SectionTitle, Telemetry, useUiStyles, WeightRow } from "@/src/components/ui";
import { useActiveJob } from "@/src/hooks";
import { useTheme } from "@/src/theme";

export default function TechnicalScreen() {
  const styles = useUiStyles();
  const { colors } = useTheme();
  const router = useRouter();
  const params = useLocalSearchParams<{ jobId?: string }>();
  const activeJob = useActiveJob();
  const jobId = params.jobId ?? activeJob?.job_id;
  const { data, isLoading } = useQuery({
    queryKey: ["technical", jobId],
    queryFn: () => api.technical(jobId as string),
    enabled: Boolean(jobId),
  });

  const ranking = data?.sample_candidate;

  return (
    <View style={styles.flex} testID="technical-screen">
      <ScreenHeader title="Technical View" onBack={() => router.back()} />
      <ScrollView contentContainerStyle={styles.scrollContent} showsVerticalScrollIndicator={false}>
        <Text style={styles.eyebrow}>FOR THE TECHNICAL JUDGES</Text>
        <Text style={styles.detailName}>See the engine work.</Text>
        <Text style={styles.mutedText}>Every number below is generated by the same deterministic screening run.</Text>

        {isLoading ? (
          <View style={styles.loadingRoot}>
            <ActivityIndicator color={colors.brand} size="large" />
            <Text style={styles.mutedText}>Calculating matching algorithm weights and telemetry...</Text>
          </View>
        ) : (
          <>
            <View style={styles.pipelineCard} testID="pipeline-stages">
              {data?.stages.map((stage, index) => (
                <View key={stage.label} style={styles.pipelineRow}>
                  <View style={styles.pipelineIcon}>
                    <Icon name="check" color={colors.brand} size={15} />
                  </View>
                  <Text style={styles.pipelineText}>{stage.label}</Text>
                  {index < (data?.stages.length ?? 0) - 1 ? <View style={styles.pipelineLine} /> : null}
                </View>
              ))}
            </View>

            <View style={styles.engineCard} testID="engine-weights">
              <SectionTitle eyebrow="HYBRID RANKING FORMULA" title="Two retrieval engines, one score" />
              <WeightRow label="Keyword retrieval" value="35%" color={colors.info} />
              <WeightRow label="Semantic retrieval" value="35%" color={colors.brand} />
              <WeightRow label="Evidence strength" value="20%" color={colors.success} />
              <WeightRow label="Requirement coverage" value="10%" color={colors.warning} />
              <Text style={styles.methodNote}>Semantic method: {data?.engine.semantic_method ?? "local deterministic embeddings"}</Text>
            </View>

            {ranking ? (
              <>
                <SectionTitle eyebrow="LIVE SAMPLE" title={`${ranking.name} · requirement telemetry`} />
                {ranking.matches.slice(0, 4).map((match) => (
                  <View key={match.requirement_id} style={styles.telemetryCard} testID={`telemetry-${match.requirement_id}`}>
                    <View style={styles.telemetryHeader}>
                      <Text style={styles.telemetryTitle}>{match.requirement}</Text>
                      <Pill label={match.match_type} tone={match.match_type === "missing" ? "error" : "success"} />
                    </View>
                    <View style={styles.telemetryValues}>
                      <Telemetry label="KEYWORD" value={match.keyword_score} />
                      <Telemetry label="SEMANTIC" value={match.semantic_score} />
                      <Telemetry label="EVIDENCE" value={match.evidence_score} />
                      <Telemetry label="WEIGHT" value={match.weight / 10} />
                    </View>
                    <Text style={styles.finalRequirement}>Final requirement score · {match.final_requirement_score.toFixed(3)}</Text>
                  </View>
                ))}
              </>
            ) : null}

            <PrimaryButton testID="technical-insights-button" label="Review JD insights" icon="alert-circle-outline" onPress={() => router.push({ pathname: "/insights", params: { jobId } })} secondary />
          </>
        )}
      </ScrollView>
    </View>
  );
}
